version: '3.9'

services: 
  
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: "azurite --loose --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --location /workspace --debug /workspace/debug.log"
    ports:
      - 10010:10000
      - 10011:10001
      - 10012:10002
    volumes:
      - azurite:/workspace

  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest 
    environment:
      - SA_PASSWORD=t_runnerP@ssw0rd
      - ACCEPT_EULA=Y
    ports:
      - 5434:1433
    volumes:
      - sqlvolume:/var/opt/mssql

  gtt-api:    
    build:
     context: ./GTT-API
     args:
        AzureWebJobsStorage: "${AzureWebJobsStorage}"
     dockerfile: src/Services/GTT/GTT.Api/Dockerfile
    ports:
    - 7071:80
    depends_on:
      - azurite    
      - sqldata
  
  reactjs:
    build:
      context: ./ReactJs
      dockerfile: Dockerfile
    ports:
    - 3000:80

volumes:
  sqlvolume:
    driver: local
  azurite:
    driver: local