name: Build and run docker containers on new build

on:
  push:
    branches:
    - "master"
    
jobs:
  build-and-run:
    runs-on: self-hosted   
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
      
    - name: Build the stack
      run: docker compose up
