name: Build and run docker containers on new build

on:
  push:
    branches:
    - "master"
    
jobs:
  build-and-run:
    runs-on: self-hosted   
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
      
    - name: Compose
      run: docker compose up -d
    - name: Integration tests
      run: docker compose up --exit-code-from integrationtest integrationtest
