name: Manually start 

on: [workflow_dispatch]
    
jobs:
  build-and-run:
    runs-on: self-hosted   
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
      
    - name: Start containers
      run: docker compose up -d
